"""
MCP Server for {WORKFLOW_NAME}
Generated by LightOn Workflow Builder

This server exposes the workflow as an MCP tool that can be used in:
- Claude Desktop
- Any MCP-compatible client
- LightOn Paradigm (when MCP support is available)
"""

import asyncio
import json
import logging
import os
from typing import Any

from dotenv import load_dotenv
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool, TextContent

from workflow import WorkflowExecutor
from paradigm_client import ParadigmClient

# Load environment variables from .env file
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Initialize MCP server
app = Server("{WORKFLOW_NAME_SLUG}")


@app.list_tools()
async def list_tools() -> list[Tool]:
    """
    List all tools available in this MCP server.
    This workflow is exposed as a single tool.
    """
    return [
        Tool(
            name="{WORKFLOW_NAME_SLUG}",
            description="""{WORKFLOW_DESCRIPTION}

This tool executes a complete workflow using the LightOn Paradigm API.

Input parameters:
{TOOL_INPUT_SCHEMA}

Output format:
{TOOL_OUTPUT_DESCRIPTION}
""",
            inputSchema={TOOL_INPUT_JSON_SCHEMA}
        )
    ]


@app.call_tool()
async def call_tool(name: str, arguments: Any) -> list[TextContent]:
    """
    Execute the workflow tool.

    Args:
        name: Tool name (should be {WORKFLOW_NAME_SLUG})
        arguments: Tool arguments as defined in inputSchema

    Returns:
        List of TextContent with workflow results
    """
    if name != "{WORKFLOW_NAME_SLUG}":
        raise ValueError("Unknown tool: {}".format(name))

    try:
        logger.info("Starting workflow execution with arguments: {}".format(json.dumps(arguments, ensure_ascii=False)))

        # Get API key from environment
        api_key = os.getenv("PARADIGM_API_KEY")
        if not api_key:
            raise ValueError("PARADIGM_API_KEY not found in environment variables. Please check your .env file.")

        base_url = os.getenv("PARADIGM_BASE_URL", "https://paradigm.lighton.ai")

        # Initialize Paradigm client
        paradigm_client = ParadigmClient(api_key=api_key, base_url=base_url)

        # Initialize workflow executor
        executor = WorkflowExecutor(paradigm_client)

        # Execute workflow
        result = await executor.execute(**arguments)

        logger.info("Workflow execution completed successfully")

        # Format result as TextContent
        return [
            TextContent(
                type="text",
                text=json.dumps(result, ensure_ascii=False, indent=2)
            )
        ]

    except Exception as e:
        logger.error("Workflow execution failed: {}".format(str(e)))
        return [
            TextContent(
                type="text",
                text=json.dumps({
                    "error": str(e),
                    "status": "failed"
                }, ensure_ascii=False, indent=2)
            )
        ]


async def main():
    """Run the MCP server using stdio transport."""
    logger.info("Starting MCP server for {WORKFLOW_NAME}")

    async with stdio_server() as (read_stream, write_stream):
        await app.run(
            read_stream,
            write_stream,
            app.create_initialization_options()
        )


if __name__ == "__main__":
    asyncio.run(main())
