"""
Workflow Combiner - Combines cell-based workflows into clean, executable code.

This module takes a workflow plan with individual cell codes and combines them
into a single, clean workflow file that:
1. Deduplicates imports and setup code
2. Wraps each cell's logic in an async function
3. Generates a main execution flow respecting layer parallelism
4. Produces production-ready, executable code

The output is suitable for:
- Standalone deployment
- Package generation (web app, MCP server)
- Code review and modification

Note: During cell execution, cells use a pre-injected ParadigmClient class
(injected by executor.py). However, exported workflows generated by this
combiner need to be self-contained, so this module generates its own API
setup and helper functions for standalone execution.
"""

import re
import ast
import logging
from typing import List, Dict, Any, Set, Tuple, Optional
from dataclasses import dataclass

from ..models import WorkflowPlan, WorkflowCell

logger = logging.getLogger(__name__)


@dataclass
class CellCodeAnalysis:
    """
    Analysis of a single cell's code.

    Attributes:
        imports: Set of import statements
        setup_code: Code that sets up API clients, constants, etc.
        core_logic: The main logic of the cell
        output_variables: Variables that this cell produces
    """
    imports: Set[str]
    setup_code: List[str]
    core_logic: str
    output_variables: List[str]


class WorkflowCombiner:
    """
    Combines cell-based workflow code into a single clean workflow.

    Takes individual cell codes and produces a unified workflow with:
    - Deduplicated imports
    - Single API setup section
    - Cell functions with proper signatures
    - Main execution flow respecting layer parallelism
    """

    # Common imports that should appear only once
    STANDARD_IMPORTS = {
        'import requests',
        'import json',
        'import asyncio',
        'import aiohttp',
        'import os',
        'import re',
        'import time',
        'from typing import Dict, Any, List, Optional, Tuple',
        'from datetime import datetime',
    }

    # Patterns for API setup code that should be deduplicated
    API_SETUP_PATTERNS = [
        r'PARADIGM_API_KEY\s*=',
        r'LIGHTON_API_KEY\s*=',
        r'API_BASE_URL\s*=',
        r'headers\s*=\s*\{[^}]*Authorization',
    ]

    def __init__(self, plan: WorkflowPlan, workflow_description: str = ""):
        """
        Initialize the combiner with a workflow plan.

        Args:
            plan: The workflow plan containing cells
            workflow_description: Human-readable workflow description
        """
        self.plan = plan
        self.workflow_description = workflow_description
        self.cells_by_layer = plan.get_cells_by_layer()

    def combine(self) -> str:
        """
        Combine all cell codes into a single clean workflow.

        Returns:
            str: Combined workflow code
        """
        # Analyze all cells
        cell_analyses: Dict[str, CellCodeAnalysis] = {}
        all_imports: Set[str] = set()

        for cell in self.plan.cells:
            if cell.generated_code:
                analysis = self._analyze_cell_code(cell)
                cell_analyses[cell.id] = analysis
                all_imports.update(analysis.imports)

        # Build the combined workflow
        sections = []

        # 1. Module docstring
        sections.append(self._generate_module_docstring())

        # 2. Imports (deduplicated)
        sections.append(self._generate_imports_section(all_imports))

        # 3. API setup (single instance)
        sections.append(self._generate_api_setup_section())

        # 4. Helper functions
        sections.append(self._generate_helper_functions())

        # 5. Cell functions
        for cell in self.plan.cells:
            if cell.id in cell_analyses:
                sections.append(self._generate_cell_function(cell, cell_analyses[cell.id]))

        # 6. Main execution function
        sections.append(self._generate_main_execution())

        # 7. Entry point
        sections.append(self._generate_entry_point())

        return "\n\n".join(filter(None, sections))

    def _analyze_cell_code(self, cell: WorkflowCell) -> CellCodeAnalysis:
        """
        Analyze a cell's code to extract imports, setup, and core logic.

        Args:
            cell: The cell to analyze

        Returns:
            CellCodeAnalysis: Analysis results
        """
        code = cell.generated_code or ""
        lines = code.split('\n')

        imports: Set[str] = set()
        setup_code: List[str] = []
        core_lines: List[str] = []

        in_imports = True
        in_setup = False

        for line in lines:
            stripped = line.strip()

            # Skip empty lines and comments at the start
            if not stripped or stripped.startswith('#'):
                if not in_imports:
                    core_lines.append(line)
                continue

            # Collect imports
            if stripped.startswith('import ') or stripped.startswith('from '):
                imports.add(stripped)
                continue

            # After imports, check for setup code
            in_imports = False

            # Check if this is API setup code
            is_setup = any(re.search(pattern, stripped) for pattern in self.API_SETUP_PATTERNS)

            if is_setup:
                setup_code.append(line)
            else:
                core_lines.append(line)

        # Clean up core logic - remove leading/trailing empty lines
        while core_lines and not core_lines[0].strip():
            core_lines.pop(0)
        while core_lines and not core_lines[-1].strip():
            core_lines.pop()

        return CellCodeAnalysis(
            imports=imports,
            setup_code=setup_code,
            core_logic='\n'.join(core_lines),
            output_variables=cell.outputs_produced
        )

    def _generate_module_docstring(self) -> str:
        """Generate the module docstring."""
        # Get layer info
        total_layers = len(self.cells_by_layer)
        parallel_layers = sum(1 for cells in self.cells_by_layer.values() if len(cells) > 1)

        return '''"""
{description}

Auto-generated workflow with {total_cells} cells in {total_layers} layers.
{parallel_info}

Cells:
{cell_list}
"""'''.format(
            description=self.workflow_description or "Combined Workflow",
            total_cells=len(self.plan.cells),
            total_layers=total_layers,
            parallel_info="Parallel execution enabled ({} parallel layers).".format(parallel_layers) if parallel_layers > 0 else "Sequential execution.",
            cell_list='\n'.join("  - Cell {}: {}".format(c.step_number, c.name) for c in self.plan.cells)
        )

    def _generate_imports_section(self, all_imports: Set[str]) -> str:
        """Generate deduplicated imports section."""
        # Separate standard library, third-party, and typing imports
        stdlib_imports = []
        typing_imports = []
        thirdparty_imports = []

        # Always include these base imports
        base_imports = {
            'import asyncio',
            'import json',
            'import os',
            'import re',
            'from typing import Dict, Any, List, Optional',
            'from datetime import datetime',
        }
        all_imports.update(base_imports)

        for imp in sorted(all_imports):
            if 'typing' in imp:
                typing_imports.append(imp)
            elif any(pkg in imp for pkg in ['requests', 'aiohttp', 'anthropic']):
                thirdparty_imports.append(imp)
            else:
                stdlib_imports.append(imp)

        sections = []
        sections.append("# Standard library imports")
        sections.extend(sorted(set(stdlib_imports)))

        if typing_imports:
            sections.append("")
            sections.append("# Type hints")
            sections.extend(sorted(set(typing_imports)))

        if thirdparty_imports:
            sections.append("")
            sections.append("# Third-party imports")
            sections.extend(sorted(set(thirdparty_imports)))

        return '\n'.join(sections)

    def _generate_api_setup_section(self) -> str:
        """Generate the API setup section with variable names matching cell code expectations."""
        return '''# =============================================================================
# API CONFIGURATION
# =============================================================================

from paradigm_client import ParadigmClient

# Load API key from environment (matching cell code expectations)
LIGHTON_API_KEY = os.environ.get("LIGHTON_API_KEY") or os.environ.get("PARADIGM_API_KEY")
LIGHTON_BASE_URL = os.environ.get("PARADIGM_BASE_URL", "https://paradigm.lighton.ai")

if not LIGHTON_API_KEY:
    raise ValueError("LIGHTON_API_KEY or PARADIGM_API_KEY environment variable is required")'''

    def _generate_helper_functions(self) -> str:
        """Generate common helper functions used by cell code."""
        return '''# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def print_output(message: str):
    """Print output message (captured for cell output)."""
    print("CELL_OUTPUT: {}".format(message))'''

    def _generate_cell_function(self, cell: WorkflowCell, analysis: CellCodeAnalysis) -> str:
        """
        Generate an async function for a cell.

        The cell's core_logic contains the full `async def execute_cell(context)`
        definition. The wrapper defines it in its scope and then calls it.

        Args:
            cell: The cell definition
            analysis: Analysis of the cell's code

        Returns:
            str: The cell function code
        """
        # Create function name from cell name
        func_name = self._cell_name_to_function(cell.name)

        # Determine inputs needed
        inputs = cell.inputs_required or []

        # Build function signature
        params = ["context: Dict[str, Any]"]

        # Build docstring parts
        layer_mode = "parallel" if len(self.cells_by_layer.get(cell.layer, [])) > 1 else "sequential"
        inputs_str = ', '.join(inputs) if inputs else 'None'
        outputs_str = ', '.join(cell.outputs_produced) if cell.outputs_produced else 'context updates'

        # Process core logic
        core_logic = self._process_core_logic(analysis.core_logic, inputs, cell.outputs_produced)

        # Build the function - core_logic defines execute_cell, then we call it
        function_code = '''
# -----------------------------------------------------------------------------
# CELL {step}: {name_upper}
# -----------------------------------------------------------------------------

async def {func_name}({params}) -> Dict[str, Any]:
    """
    Cell {step}: {name}

    {description}

    Layer: {layer} ({layer_mode})

    Inputs: {inputs_str}
    Outputs: {outputs_str}
    """

    # Cell logic (defines execute_cell)
{core_logic}

    # Execute the cell and return its result
    return await execute_cell(context)
'''.format(
            step=cell.step_number,
            name_upper=cell.name.upper(),
            name=cell.name,
            func_name=func_name,
            params=', '.join(params),
            description=cell.description,
            layer=cell.layer,
            layer_mode=layer_mode,
            inputs_str=inputs_str,
            outputs_str=outputs_str,
            core_logic=self._indent_code(core_logic, 4)
        )

        return function_code

    def _generate_main_execution(self) -> str:
        """Generate the main execution function with layer parallelism."""
        layers = sorted(self.cells_by_layer.keys())

        layer_code_blocks = []

        for layer_num in layers:
            cells = self.cells_by_layer[layer_num]

            if len(cells) == 1:
                # Sequential execution
                cell = cells[0]
                func_name = self._cell_name_to_function(cell.name)
                block = '    # Layer {layer}: {name}\n'.format(layer=layer_num, name=cell.name)
                block += '    print_output("Executing Layer {layer}: {name}")\n'.format(layer=layer_num, name=cell.name)
                block += '    layer_{layer}_result = await {func}(context)\n'.format(layer=layer_num, func=func_name)
                block += '    context.update(layer_{layer}_result)'.format(layer=layer_num)
                layer_code_blocks.append(block)
            else:
                # Parallel execution
                cell_names = [c.name for c in cells]
                func_calls = ["{}(context.copy())".format(self._cell_name_to_function(c.name)) for c in cells]
                names_joined = ', '.join(cell_names)

                block = '    # Layer {layer}: PARALLEL ({names})\n'.format(layer=layer_num, names=names_joined)
                block += '    print_output("Executing Layer {layer} in parallel: {names}")\n'.format(layer=layer_num, names=names_joined)
                block += '    layer_{layer}_results = await asyncio.gather(\n'.format(layer=layer_num)
                block += '        ' + (',\n        ').join(func_calls) + '\n'
                block += '    )\n'
                block += '    # Merge results from parallel cells\n'
                block += '    for result in layer_{layer}_results:\n'.format(layer=layer_num)
                block += '        context.update(result)'
                layer_code_blocks.append(block)

        layers_joined = '\n\n'.join(layer_code_blocks)

        return '''# =============================================================================
# MAIN WORKFLOW EXECUTION
# =============================================================================

async def run_workflow(
    user_input: str,
    attached_file_ids: Optional[List[int]] = None
) -> Dict[str, Any]:
    """
    Execute the complete workflow.

    Args:
        user_input: User's input query
        attached_file_ids: Optional list of document file IDs

    Returns:
        Dict containing all workflow outputs
    """
    # Initialize context with inputs
    context: Dict[str, Any] = {{
        "user_input": user_input,
        "attached_file_ids": attached_file_ids or []
    }}

    print_output("Starting workflow with input: {{}}...".format(user_input[:100]))

{layers}

    print_output("Workflow completed successfully!")

    return context'''.format(layers=layers_joined)

    def _generate_entry_point(self) -> str:
        """Generate the entry point for standalone execution."""
        return '''# =============================================================================
# ENTRY POINT
# =============================================================================

async def execute_workflow(user_input: str, file_ids: Optional[List[int]] = None) -> Dict[str, Any]:
    """
    Async entry point for workflow execution.

    Args:
        user_input: User's input query
        file_ids: Optional list of document file IDs

    Returns:
        Dict containing all workflow outputs
    """
    return await run_workflow(user_input, file_ids)


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python workflow.py <user_input> [file_id1,file_id2,...]")
        sys.exit(1)

    user_input = sys.argv[1]
    file_ids = None

    if len(sys.argv) > 2:
        file_ids = [int(fid) for fid in sys.argv[2].split(",")]

    result = asyncio.run(execute_workflow(user_input, file_ids))
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))'''

    def _cell_name_to_function(self, name: str) -> str:
        """Convert a cell name to a valid Python function name."""
        # Remove special characters and convert to snake_case
        name = re.sub(r'[^\w\s]', '', name)
        name = re.sub(r'\s+', '_', name)
        name = name.lower()
        # Ensure it starts with a letter
        if name and name[0].isdigit():
            name = 'cell_' + name
        return "cell_{}".format(name) if name else "cell_unnamed"

    def _process_core_logic(self, code: str, inputs: List[str], outputs: List[str]) -> str:
        """
        Process core logic to work within the function context.

        The core logic should contain an `async def execute_cell(context)` definition.
        If not present (edge case), wraps the code in a minimal execute_cell function.
        """
        if not code.strip():
            return 'async def execute_cell(context):\n    return {}'

        # Verify execute_cell is defined in the core logic
        if 'async def execute_cell' not in code:
            # Wrap the raw code in an execute_cell function as fallback
            logger.warning("Core logic missing execute_cell definition, wrapping automatically")
            indented = self._indent_code(code, 4)
            return 'async def execute_cell(context):\n{indented}\n    return {{}}'.format(
                indented=indented
            )

        return code

    def _generate_input_extraction(self, inputs: List[str]) -> str:
        """Generate code to extract inputs from context."""
        if not inputs:
            return ""

        lines = []
        for inp in inputs:
            lines.append('    {var} = context.get("{var}")'.format(var=inp))

        return '\n'.join(lines)

    def _generate_output_dict(self, outputs: List[str]) -> str:
        """Generate the return dictionary for outputs."""
        if not outputs:
            return "{}"

        items = ['"{var}": {var}'.format(var=out) for out in outputs]

        if len(items) <= 2:
            return "{" + ", ".join(items) + "}"
        else:
            return "{\n        " + ",\n        ".join(items) + "\n    }"

    def _indent_code(self, code: str, spaces: int) -> str:
        """Indent code by a number of spaces."""
        indent = ' ' * spaces
        lines = code.split('\n')
        return '\n'.join(indent + line if line.strip() else line for line in lines)


def combine_workflow_cells(plan: WorkflowPlan, workflow_description: str = "") -> str:
    """
    Convenience function to combine workflow cells into clean code.

    Args:
        plan: The workflow plan containing cells
        workflow_description: Human-readable workflow description

    Returns:
        str: Combined, clean workflow code
    """
    combiner = WorkflowCombiner(plan, workflow_description)
    return combiner.combine()
