"""
Workflow Domain Models

This module defines the core domain models for the workflow system:
- Workflow: Represents a workflow with generated code and metadata
- WorkflowExecution: Tracks individual workflow execution instances
- ExecutionStatus: Enumeration of possible execution states
- CodeGenerationContext: Context for code generation operations
- WorkflowCell: Represents a single executable cell in a cell-based workflow
- WorkflowPlan: High-level plan containing the sequence of cells
- CellStatus: Enumeration of cell execution states

Key Features:
    - Dataclass-based models for immutability and type safety
    - UUID-based unique identifiers
    - Comprehensive status tracking with timestamps
    - Execution timing and error handling
    - Context management for code generation
    - Cell-based workflow support for step-by-step execution

Architecture:
    - Domain-driven design with clear separation of concerns
    - Status management with proper state transitions
    - Comprehensive metadata tracking for debugging and monitoring
    - Cell-based execution model for progressive output display
"""

from datetime import datetime
from typing import Optional, Dict, Any, List
from dataclasses import dataclass, field
from enum import Enum
import uuid


class CellStatus(str, Enum):
    """
    Enumeration of workflow cell status values.

    States:
        PENDING: Cell not yet generated or executed
        GENERATING: Code is being generated by Claude
        READY: Code generated, ready to execute
        EXECUTING: Cell is currently running
        COMPLETED: Cell finished successfully
        FAILED: Cell execution failed
        SKIPPED: Cell was skipped due to earlier failure
    """
    PENDING = "pending"
    GENERATING = "generating"
    READY = "ready"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class ExecutionStatus(str, Enum):
    """
    Enumeration of workflow execution status values.
    
    States:
        PENDING: Execution has been queued but not started
        RUNNING: Execution is currently in progress
        COMPLETED: Execution finished successfully
        FAILED: Execution failed due to an error
        TIMEOUT: Execution was terminated due to timeout
    """
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    TIMEOUT = "timeout"

@dataclass
class Workflow:
    """
    Represents a workflow with AI-generated code and metadata.
    
    A workflow contains the user's description, AI-generated Python code,
    status information, and timing data. Workflows can be executed multiple
    times with different inputs.
    
    Attributes:
        id: Unique identifier (UUID)
        name: Optional human-readable name
        description: Natural language description provided by user
        generated_code: AI-generated Python code for execution
        status: Current workflow status
        created_at: Timestamp of creation
        updated_at: Timestamp of last modification
        error: Error message if workflow creation failed
        context: Additional context used during code generation
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: Optional[str] = None
    description: str = ""
    generated_code: Optional[str] = None
    status: str = "created"
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    error: Optional[str] = None
    context: Optional[Dict[str, Any]] = None
    
    def update_status(self, status: str, error: Optional[str] = None):
        """
        Update workflow status and timestamp.
        
        Updates the workflow status, sets the updated timestamp to current time,
        and optionally records an error message.
        
        Args:
            status: New status value
            error: Optional error message to record
        """
        self.status = status
        self.updated_at = datetime.utcnow()
        if error:
            self.error = error

@dataclass
class WorkflowExecution:
    """
    Represents a single execution instance of a workflow.
    
    Tracks the execution of a workflow with specific user input,
    including results, timing, and any errors that occurred.
    
    Attributes:
        id: Unique execution identifier (UUID)
        workflow_id: ID of the parent workflow
        user_input: Input provided by user for this execution
        result: Execution result or None if not completed
        status: Current execution status
        execution_time: Time taken to execute (seconds)
        error: Error message if execution failed
        created_at: Timestamp when execution started
        completed_at: Timestamp when execution finished (if applicable)
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    workflow_id: str = ""
    user_input: str = ""
    result: Optional[str] = None
    status: ExecutionStatus = ExecutionStatus.PENDING
    execution_time: Optional[float] = None
    error: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    
    def mark_completed(self, result: str, execution_time: float):
        """
        Mark execution as successfully completed.
        
        Sets the execution status to COMPLETED, records the result,
        execution time, and completion timestamp.
        
        Args:
            result: The execution result string
            execution_time: Time taken to execute in seconds
        """
        self.result = result
        self.status = ExecutionStatus.COMPLETED
        self.execution_time = execution_time
        self.completed_at = datetime.utcnow()
    
    def mark_failed(self, error: str, execution_time: Optional[float] = None):
        """
        Mark execution as failed with error details.
        
        Sets the execution status to FAILED, records the error message,
        optional execution time, and completion timestamp.
        
        Args:
            error: Error message describing the failure
            execution_time: Optional time taken before failure (seconds)
        """
        self.error = error
        self.status = ExecutionStatus.FAILED
        self.execution_time = execution_time
        self.completed_at = datetime.utcnow()

@dataclass
class CodeGenerationContext:
    """
    Context information for AI code generation.

    Provides configuration and context data used during the
    code generation process to influence the AI's output.

    Attributes:
        available_tools: List of tool names available to generated code
        max_steps: Maximum number of workflow steps allowed
        timeout_seconds: Maximum execution time allowed
        additional_context: Extra context data for specialized workflows
    """
    """Context for code generation"""
    available_tools: List[str] = field(default_factory=lambda: ["paradigm_search", "chat_completion"])
    max_steps: int = 50
    timeout_seconds: int = 300
    additional_context: Optional[Dict[str, Any]] = None


@dataclass
class WorkflowCell:
    """
    Represents a single executable cell within a workflow.

    Each cell is a discrete step that:
    - Has its own generated code
    - Receives inputs from previous cells via execution_context
    - Produces outputs that can be consumed by subsequent cells
    - Can be executed independently once its dependencies are met

    Attributes:
        id: Unique cell identifier (UUID)
        workflow_id: ID of the parent workflow
        step_number: Sequential position in the workflow (1-indexed)
        name: Short descriptive name (e.g., "Document Search")
        description: Detailed description of what this cell does
        layer: Execution layer number (1, 2, 3...) - cells in same layer run in parallel
        sublayer_index: Position within layer (1, 2, 3...) - for display as X.1, X.2, X.3
        depends_on: List of cell IDs this cell depends on (data dependencies)
        inputs_required: Variable names needed from previous cells
        outputs_produced: Variable names this cell will produce
        paradigm_tools_used: List of Paradigm API tools used
        generated_code: The Python code for this cell
        status: Current cell status
        output: Human-readable output after execution
        output_variables: Dictionary of variables produced
        error: Error message if cell failed
        execution_time: Time taken to execute (seconds)
        created_at: Timestamp of creation
        executed_at: Timestamp of execution completion
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    workflow_id: str = ""
    step_number: int = 0

    # Description and planning
    name: str = ""
    description: str = ""

    # Parallelization - layer-based execution ordering
    # Cells in the same layer execute in parallel
    # Layer N+1 only starts after all cells in layer N complete
    layer: int = 1  # Execution layer (1, 2, 3...)
    sublayer_index: int = 1  # Position within layer (for display: 1.1, 1.2, 2.1, etc.)

    # Dependencies and data flow
    # depends_on tracks DATA dependencies (which cell outputs this cell needs)
    # This is different from layer ordering (execution timing)
    depends_on: List[str] = field(default_factory=list)
    inputs_required: List[str] = field(default_factory=list)
    outputs_produced: List[str] = field(default_factory=list)
    paradigm_tools_used: List[str] = field(default_factory=list)

    # Code generation
    generated_code: Optional[str] = None
    code_description: Optional[str] = None  # Human-readable explanation of what the code does
    status: CellStatus = CellStatus.PENDING

    # Execution results
    output: Optional[str] = None
    output_variables: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    execution_time: Optional[float] = None

    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    executed_at: Optional[datetime] = None

    def mark_generating(self):
        """Mark cell as currently generating code"""
        self.status = CellStatus.GENERATING

    def mark_ready(self, code: str, code_description: Optional[str] = None):
        """Mark cell as ready with generated code and description"""
        self.generated_code = code
        if code_description:
            self.code_description = code_description
        self.status = CellStatus.READY

    def mark_executing(self):
        """Mark cell as currently executing"""
        self.status = CellStatus.EXECUTING

    def mark_completed(self, output: str, variables: Dict[str, Any], execution_time: float):
        """Mark cell as successfully completed"""
        self.output = output
        self.output_variables = variables
        self.execution_time = execution_time
        self.status = CellStatus.COMPLETED
        self.executed_at = datetime.utcnow()

    def mark_failed(self, error: str, execution_time: Optional[float] = None):
        """Mark cell as failed with error details"""
        self.error = error
        self.execution_time = execution_time
        self.status = CellStatus.FAILED
        self.executed_at = datetime.utcnow()

    def mark_skipped(self):
        """Mark cell as skipped due to earlier failure"""
        self.status = CellStatus.SKIPPED

    def get_display_step(self) -> str:
        """
        Get the display step number (e.g., '2.1', '2.2') for UI display.

        Returns:
            str: Formatted step number like '1.1', '2.3', etc.
        """
        return "{}.{}".format(self.layer, self.sublayer_index)

    def to_dict(self) -> Dict[str, Any]:
        """Convert cell to dictionary for serialization"""
        return {
            "id": self.id,
            "workflow_id": self.workflow_id,
            "step_number": self.step_number,
            "name": self.name,
            "description": self.description,
            "layer": self.layer,
            "sublayer_index": self.sublayer_index,
            "display_step": self.get_display_step(),
            "depends_on": self.depends_on,
            "inputs_required": self.inputs_required,
            "outputs_produced": self.outputs_produced,
            "paradigm_tools_used": self.paradigm_tools_used,
            "generated_code": self.generated_code,
            "code_description": self.code_description,
            "status": self.status.value if isinstance(self.status, CellStatus) else self.status,
            "output": self.output,
            "output_variables": self.output_variables,
            "error": self.error,
            "execution_time": self.execution_time,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "WorkflowCell":
        """Create cell from dictionary"""
        cell = cls(
            id=data.get("id", str(uuid.uuid4())),
            workflow_id=data.get("workflow_id", ""),
            step_number=data.get("step_number", 0),
            name=data.get("name", ""),
            description=data.get("description", ""),
            layer=data.get("layer", 1),
            sublayer_index=data.get("sublayer_index", 1),
            depends_on=data.get("depends_on", []),
            inputs_required=data.get("inputs_required", []),
            outputs_produced=data.get("outputs_produced", []),
            paradigm_tools_used=data.get("paradigm_tools_used", []),
            generated_code=data.get("generated_code"),
            code_description=data.get("code_description"),
            output=data.get("output"),
            output_variables=data.get("output_variables"),
            error=data.get("error"),
            execution_time=data.get("execution_time"),
        )
        # Handle status
        status_val = data.get("status", "pending")
        if isinstance(status_val, str):
            cell.status = CellStatus(status_val)
        else:
            cell.status = status_val
        return cell


@dataclass
class WorkflowPlan:
    """
    High-level plan for a workflow, produced during planning phase.

    Contains the sequence of cells to be generated and executed,
    along with their dependencies and data flow schema.

    Attributes:
        id: Unique plan identifier (UUID)
        workflow_id: ID of the parent workflow
        description: Original user description
        cells: List of WorkflowCell definitions
        shared_context_schema: Variable name to type description mapping
        status: Current plan status
        current_cell_index: Index of cell currently being processed
        created_at: Timestamp of creation
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    workflow_id: str = ""
    description: str = ""

    # Planning output
    cells: List[WorkflowCell] = field(default_factory=list)
    shared_context_schema: Dict[str, str] = field(default_factory=dict)

    # Status tracking
    status: str = "created"  # created, planning, ready, executing, completed, failed
    current_cell_index: int = 0

    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> Dict[str, Any]:
        """Convert plan to dictionary for serialization"""
        return {
            "id": self.id,
            "workflow_id": self.workflow_id,
            "description": self.description,
            "cells": [cell.to_dict() for cell in self.cells],
            "shared_context_schema": self.shared_context_schema,
            "status": self.status,
            "current_cell_index": self.current_cell_index,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "WorkflowPlan":
        """Create plan from dictionary"""
        plan = cls(
            id=data.get("id", str(uuid.uuid4())),
            workflow_id=data.get("workflow_id", ""),
            description=data.get("description", ""),
            shared_context_schema=data.get("shared_context_schema", {}),
            status=data.get("status", "created"),
            current_cell_index=data.get("current_cell_index", 0),
        )
        # Parse cells
        cells_data = data.get("cells", [])
        plan.cells = [WorkflowCell.from_dict(c) for c in cells_data]
        return plan

    def get_cells_by_layer(self) -> Dict[int, List[WorkflowCell]]:
        """
        Group cells by their execution layer.

        Returns:
            Dict[int, List[WorkflowCell]]: Mapping of layer number to list of cells
        """
        layers: Dict[int, List[WorkflowCell]] = {}
        for cell in self.cells:
            if cell.layer not in layers:
                layers[cell.layer] = []
            layers[cell.layer].append(cell)
        return layers

    def get_max_layer(self) -> int:
        """
        Get the maximum layer number in the plan.

        Returns:
            int: Maximum layer number, or 0 if no cells
        """
        if not self.cells:
            return 0
        return max(cell.layer for cell in self.cells)

    def is_parallel_workflow(self) -> bool:
        """
        Check if this workflow has any parallel layers (more than one cell in a layer).

        Returns:
            bool: True if any layer has multiple cells
        """
        layers = self.get_cells_by_layer()
        return any(len(cells) > 1 for cells in layers.values())